"""empty message

Revision ID: 003ed0beff2a
Revises: 5b01f14eb743
Create Date: 2026-01-06 21:36:17.449352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003ed0beff2a'
down_revision: Union[str, None] = '5b01f14eb743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('is_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_sold')
    op.drop_column('products', 'creation_date')
    # ### end Alembic commands ###
