"""empty message

Revision ID: db7dbbb88323
Revises: 886e73daead9
Create Date: 2025-12-27 12:33:22.418333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7dbbb88323'
down_revision: Union[str, None] = '886e73daead9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediator_messages', sa.Column('is_recipient_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediator_messages', 'is_recipient_read')
    # ### end Alembic commands ###
