"""Start work with DataBase

Revision ID: 9fd075d2d503
Revises: 
Create Date: 2025-10-18 17:53:56.263844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd075d2d503'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediator_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('mediator_chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediator_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('sender_date', sa.DateTime(), nullable=False),
    sa.Column('media_path', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('money_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('money_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('media_path', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ref_catalogs')
    op.drop_table('products')
    op.drop_table('money_balance')
    op.drop_table('mediator_messages')
    op.drop_table('mediator_chats')
    # ### end Alembic commands ###
